### PR TITLE
Robust tracking and drone controller

### PR DESCRIPTION
**Pull request by squeakus**
I haven't able to stream the tello feed to the tracker but the two parts are working separately. I also added some documentation

### CODE REVIEW

**Comment by lebuckle** [comment]
Approving this post 11pm is above my pay grade, will review tomorrow

**Comment by lebuckle** [comment]
On a Sunday need I add

**Comment by squeakus** [comment]
Thank you for your kind comments on my voluntary and unpaid contributions to your open source project. I hope you will find some time in your busy schedule galavanting between openings and hackathons to review my meager code offerings.

**Comment by lebuckle** [comment]
Approved!

**Comment by squeakus** [comment]
I think you need to merge these changes, I don't have write access.

**Pull request merged**
